window.__abilityEditModalsHTML__ = [
    '<!-- 编辑弹窗 -->',
    '<div class="modal-overlay" id="create-modal-overlay">',
    '    <div class="modal-content create-modal">',
    '        <div class="modal-header">',
    '            <h3 id="create-modal-title">编辑</h3>',
    '            <button class="modal-close" id="create-modal-close"><i class="fas fa-times"></i></button>',
    '        </div>',
    '        <div class="modal-body">',
    '            <form id="create-form">',
    '                <div class="form-group">',
    '                    <label>名称 <span class="required">*</span></label>',
    '                    <input type="text" class="form-input" id="form-name" required placeholder="请输入名称">',
    '                </div>',
    '                <div class="form-group">',
    '                    <label>描述</label>',
    '                    <textarea class="form-textarea" id="form-desc" rows="3" placeholder="请输入描述"></textarea>',
    '                </div>',
    '                <div class="form-group">',
    '                    <label>标签（<span id="form-tag-count">0</span>）</label>',
    '                    <div class="form-tags" id="form-tags"></div>',
    '                    <button type="button" class="btn-add" id="add-tag-btn"><i class="fas fa-plus"></i> 添加</button>',
    '                </div>',
    '                <div class="form-group">',
    '                    <label>关联知识点（<span id="form-knowledge-count">0</span>）</label>',
    '                    <div class="form-tags" id="form-knowledge-tags"></div>',
    '                    <button type="button" class="btn-add" id="add-knowledge-btn"><i class="fas fa-plus"></i> 添加</button>',
    '                </div>',
    '            </form>',
    '        </div>',
    '        <div class="modal-footer">',
    '            <button class="btn btn-cancel" id="create-btn-cancel">取消</button>',
    '            <button class="btn btn-confirm" id="create-btn-confirm">确定</button>',
    '        </div>',
    '    </div>',
    '</div>',
    '',
    '<!-- 标签选择弹窗 -->',
    '<div class="modal-overlay" id="tag-modal-overlay">',
    '    <div class="modal-content tag-modal">',
    '        <div class="modal-header">',
    '            <h3>添加标签</h3>',
    '            <button class="modal-close" id="tag-modal-close"><i class="fas fa-times"></i></button>',
    '        </div>',
    '        <div class="modal-body">',
    '            <div class="tag-modal-content">',
    '                <div class="tag-modal-left">',
    '                    <div class="tag-modal-left-header">',
    '                        <button class="btn-text" id="new-tag-btn"><i class="fas fa-plus"></i> 新建标签</button>',
    '                        <div class="tag-search"><input type="text" class="tag-search-input" id="tag-search-input" placeholder="搜索标签"></div>',
    '                    </div>',
    '                    <div class="tag-new-form" id="tag-new-form" style="display:none;">',
    '                        <input type="text" class="form-input" id="new-tag-name" placeholder="输入标签名称">',
    '                        <div class="tag-new-actions">',
    '                            <button class="btn-sm btn-confirm" id="new-tag-confirm">确认</button>',
    '                            <button class="btn-sm btn-cancel" id="new-tag-cancel">取消</button>',
    '                        </div>',
    '                    </div>',
    '                    <ul class="tag-list" id="tag-list"></ul>',
    '                </div>',
    '                <div class="tag-modal-right">',
    '                    <div class="tag-selected-header">已选中 <span id="tag-selected-count">0</span> 个</div>',
    '                    <div class="tag-selected-list" id="tag-selected-list"></div>',
    '                </div>',
    '            </div>',
    '        </div>',
    '        <div class="modal-footer">',
    '            <button class="btn btn-cancel" id="tag-btn-cancel">取消</button>',
    '            <button class="btn btn-confirm" id="tag-btn-confirm">确定</button>',
    '        </div>',
    '    </div>',
    '</div>',
    '',
    '<!-- 知识点关联弹窗 -->',
    '<div class="modal-overlay" id="knowledge-modal-overlay">',
    '    <div class="modal-content knowledge-modal">',
    '        <div class="modal-header">',
    '            <h3>关联知识点</h3>',
    '            <button class="modal-close" id="knowledge-modal-close"><i class="fas fa-times"></i></button>',
    '        </div>',
    '        <div class="modal-body">',
    '            <div class="knowledge-modal-content">',
    '                <div class="knowledge-modal-left">',
    '                    <div class="knowledge-modal-left-header">',
    '                        <span class="knowledge-count">共 <em id="knowledge-tree-count">0</em> 个知识点</span>',
    '                    </div>',
    '                    <ul class="knowledge-tree" id="knowledge-tree"></ul>',
    '                </div>',
    '                <div class="knowledge-modal-right">',
    '                    <div class="knowledge-selected-header">已选中 <span id="knowledge-selected-count">0</span> 个</div>',
    '                    <div class="knowledge-selected-list" id="knowledge-selected-list"></div>',
    '                </div>',
    '            </div>',
    '        </div>',
    '        <div class="modal-footer">',
    '            <button class="btn btn-cancel" id="knowledge-btn-cancel">取消</button>',
    '            <button class="btn btn-confirm" id="knowledge-btn-confirm">确定</button>',
    '        </div>',
    '    </div>',
    '</div>',
    '',
    '<!-- 确认提示弹窗 -->',
    '<div class="modal-overlay" id="confirm-modal-overlay">',
    '    <div class="modal-content confirm-modal">',
    '        <div class="modal-header">',
    '            <h3>提示</h3>',
    '            <button class="modal-close" id="confirm-modal-close"><i class="fas fa-times"></i></button>',
    '        </div>',
    '        <div class="modal-body">',
    '            <div class="confirm-text" id="confirm-text"></div>',
    '        </div>',
    '        <div class="modal-footer">',
    '            <button class="btn btn-cancel" id="confirm-btn-cancel">取消</button>',
    '            <button class="btn btn-confirm" id="confirm-btn-confirm">确定</button>',
    '        </div>',
    '    </div>',
    '</div>'
].join('');
